services:
    go_backend:
        build: 
            context: https://github.com/Laurens-Hertzer/Online_Go.git#main
            dockerfile: Dockerfile
        container_name: online_go_app
        environment:
            - DATABASE_URL=${DATABASE_URL}
            - SESSION_SECRET=${SESSION_SECRET}
            - NODE_ENV=${NODE_ENV}
            - ALLOWED_ORIGIN=${ALLOWED_ORIGIN}
            - DB_SSL=${DB_SSL}
        networks:
            - caddy_net
            - internal_net_go
        depends_on:
            postgres:
                condition: service_healthy
        restart: always

    postgres:
        image: postgres:16-alpine
        container_name: online_go_db
        networks:
            - internal_net_go
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
            interval: 5s
            timeout: 5s
            retries: 5
        restart: always

    adminer:
        image: adminer
        restart: always
        ports:
            - 8081:8080

volumes:
    postgres_data:

networks:
    caddy_net:
        external: true
    internal_net_go:
